### ISSUE TITLE
No way to create 1.1 instance

### ISSUE THREAD

**Issue by pdelbarba** [MaikKlein/ash#179] opened 2019-01-27 02:01 UTC
No create_instance() method exists for EntryV1_1 so it appears that it's only possible to create V1.0 instances.

**Comment by MaikKlein** [comment] 2019-01-27 07:45
There are no versioned loaders any more. Just call `create_instance` and you can use 1.1 functions with `DeviceV1_1` etc. Also make sure that you request that instance to be 1.1.

https://docs.rs/ash/0.27.1/ash/struct.Instance.html

**Comment by pdelbarba** [comment] 2019-01-27 18:49
I'm really sorry, I'm still somewhat new to rust.  The only `create_instance` in the code base is implemented for the trait `EntryV1_0` so do I use that?

I assume by requesting the instance be 1.1 you mean doing the following:
```
let app_info = vk::ApplicationInfo::builder()
    ...
    .api_version(ash::vk_make_version!(1, 1, 0));

```
Is this the long term intended behavior?  If so, I'd be glad to update the example code if you want, once I get this figured out.

**Comment by MaikKlein** [comment] 2019-01-27 21:12
Yes that is the intended behavior. The samples don't use any 1.1 features.

**Comment by MaikKlein** [comment] 2019-02-01 08:05
I am closing this, feel free to reopen it if you still have an issue.

**Closed by MaikKlein** 2019-02-01 08:05 UTC
